error id: 88TkfInfPLDhrbUNJqtZoA==
### Bloop error:

called from utest.runner.BaseRunner.runSuite(scala.collection.immutable.Seq,java.lang.String,sbt.testing.EventHandler,sbt.testing.TaskDef)scala.concurrent.Future
#### Short summary: 

called from utest.runner.BaseRunner.runSuite(scala.collection.immutable.Seq,java.lang.String,sbt.tes...